config/routes.rb
Rails.application.routes.draw do
  resources :line_items
  resources :carts
  resources :roles
  resources :user_profiles

  root "user_profiles#index"
  # get "home/index", to: 'home#index'

  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }

  resources :charges

  resources :conversations do
    resources :messages
  end

end

app/models/user_profile.rb
class UserProfile < ApplicationRecord
  belongs_to :user
  validates_associated :user
  serialize :images, Array
  mount_uploaders :images, ImageUploader

  has_many :line_items
  before_destroy :ensure_not_referenced_by_any_line_item

  private
    def ensure_not_referenced_by_any_line_item
      unless line_items.empty?
        errors.add(:base, 'Line Items present')
        throw :abort
      end
    end

  def self.search(search)
    where("name LIKE ?", "%#{search}%")
  end

end

app/controllers/user_profiles_controller.rb
class UserProfilesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user_profile, only: [:show, :edit, :update, :destroy]
  # load_and_authorize_resource
  # GET /user_profiles
  # GET /user_profiles.json
  def index
    if params[:search]
      @user_profiles = UserProfile.search(params[:search]).order("created_at DESC")
    else
      @user_profiles = UserProfile.all.order('created_at DESC')
    end
  end

  # GET /user_profiles/1
  # GET /user_profiles/1.json
  def show
    @user_profile = UserProfile.find(params[:id])

  end

  # GET /user_profiles/new
  def new
    @user_profile = UserProfile.new
  end

  # GET /user_profiles/1/edit
  def edit
    @user_profile=UserProfile.find(params[:id])
    if current_user == @user_profile.user
      @user_profile.update
    end
      redirect_to root_path
  end

  # POST /user_profiles
  # POST /user_profiles.json
  def create
    @user_profile = UserProfile.new(user_profile_params)
    @user_profile.user_id = current_user.id if current_user
    current_user.update_attributes(role_id: Role.find(2).id)

    respond_to do |format|
      if @user_profile.save
        format.html { redirect_to @user_profile, notice: 'User profile was successfully created.' }
        format.json { render :show, status: :created, location: @user_profile }
      else
        format.html { render :new }
        format.json { render json: @user_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_profiles/1
  # PATCH/PUT /user_profiles/1.json
  def update

    respond_to do |format|
      if @user_profile.update(user_profile_params)
        format.html { redirect_to @user_profile, notice: 'User profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_profile }
      else
        format.html { render :edit }
        format.json { render json: @user_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_profiles/1
  # DELETE /user_profiles/1.json
  def destroy
    @user_profile=UserProfile.find(params[:id])
    if current_user == @user_profile.user
      @user_profile.destroy
    end
    redirect_to root_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_profile
      @user_profile = UserProfile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_profile_params
      params.require(:user_profile).permit(:name, :age, :hometown, :instagram, :portfolio, {images: []})
    end
end

app/helpers/user_profiles_helper.rb
module UserProfilesHelper
end

app/views/user_profiles/_form.html.erb
<div class="row">
  <div class ="col s12 m10 offset-m1 l8 offset-l2">

<%= form_for(user_profile) do |f| %>
  <% if user_profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user_profile.errors.count, "error") %> prohibited this user_profile from being saved:</h2>

      <ul>
      <% user_profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :age %>
    <%= f.number_field :age %>
  </div>

  <div class="field">
    <%= f.label :hometown %>
    <%= f.text_field :hometown %>
  </div>

  <div class="field">
    <%= f.label :instagram %>
    <%= f.url_field :instagram %>
  </div>

  <div class="field">
    <%= f.label :portfolio %>
    <%= f.url_field :portfolio %>
  </div>

  <div class="field">
    <%= f.label :upload_square_transparent_design %>
    <%= f.file_field :images, multiple: true %>
  </div>

<br>
  <div class="actions">
    <%= f.submit %>
  </div>



<% end %>

</end>
</end>

app/views/user_profiles/edit.html.erb
<div class="row">
  <div class ="col s12 m10 offset-m1 l8 offset-l2">

<h1>Editing User Profile</h1>

<%= render 'form', user_profile: @user_profile %>

<%= link_to 'Show', @user_profile %> |
<%= link_to 'Back', user_profiles_path %>

  </div>
</div>

app/views/user_profiles/index.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="cover-image">
      <img class="indexcover" src="<%= asset_path 'Optimizedwaverocks.png' %>" alt="Unlabelled Designs Wave">
  </div>
</div>

<div class ="row">
  <div class="col l6 m8 s12 offset-s6 offset-m2 offset-l3">

    <p><%= link_to 'Sell Your Designs', new_user_profile_path %></p>

    <%= form_tag(user_profiles_path, :method => "get", id: "search-form") do %>
    <%= text_field_tag :search, params[:search], placeholder: "Search Designers" %>
    <%= submit_tag "Search" %>
    <% end %>

    <% if !@user_profiles.present? %>
      <p>There are no designers that match your search <%= params[:search] %>.</p>
    <% end %>
  </div>
</div>

<br>
<br>
<br>

<% @user_profiles.each do |user_profile| %>
  <div class= "row">
  <div class="card col l6 m8 s12 offset-s6 offset-m2 offset-l3">
    <p><%=user_profile.name%></p>
    <p><%=user_profile.hometown%></p>
    <p><%=user_profile.age %></p>

    <div class="card-image">
      <div class ="image-style">
        <% user_profile.images.each do |image| %>
          <%= image_tag(image.url, class:"design") %>
        <% end %>
      </div>
    </div>
      <div class="card-content">
        <p><em>Instagram:   </em><a href="<%= user_profile.instagram %>"><i class="fa fa-instagram" aria-hidden="true"></i></a><p>
        <p><em>Portfolio:   </em><a href="<%= user_profile.portfolio %>"><i class="fa fa-desktop" aria-hidden="true"></i></a><p>
      </div>
      <!-- <div class="card-action"> -->
        <p>
          <%= link_to 'View', user_profile_path(user_profile)%>
          <% if user_profile.user == current_user %>
            <%= link_to "Edit", edit_user_profile_path(user_profile) %>
            <%= link_to "Delete", user_profile_path(user_profile), method: :delete %>
          <% end %>
        </p>
      </div>
    </div>
  </div>
<% end %>

app/views/user_profiles/new.html.erb
<div class="row">
  <div class ="col s12 m10 offset-m1 l8 offset-l2">
<h1>Sell Your Designs</h1>

<%= render 'form', user_profile: @user_profile %>

<%= link_to 'Back', user_profiles_path %>

</div>
</div>

app/views/user_profiles/show.html.erb
<p id="notice"><%= notice %></p>
<%= link_to 'Back to home', user_profiles_path %>

<div class= "row">

    <div class="card col l6  m8 s12 offset-s6 offset-m2 offset-l3">
      <div class="">
        <p><%=@user_profile.name%></p>
        <p><%=@user_profile.hometown%></p>

        <div class="card-image">
          <div class ="image-style">
            <% @user_profile.images.each do |image| %>
            <br>
            <br>
            <br>
            <br>
            <%= image_tag(image.url, class:"design") %>

          </div>
        </div>

        <div class="card-content">
          <p><a href="<%= @user_profile.instagram %>"><i class="fa fa-instagram" aria-hidden="true"></i></a><p>
          <p><a href="<%= @user_profile.portfolio %>"><i class="fa fa-desktop" aria-hidden="true"></i></a><p>



        <div class="card-action">
          <% if @user_profile.user == current_user %>
          <p><%= link_to "Edit", edit_user_profile_path(@user_profile) %></p>
          <p><%= link_to "Delete", user_profile_path(@user_profile), method: :delete%></p>
          <% end %>
          <p><%= button_to 'Add to Cart', line_items_path(user_profile_id: @user_profile) %></p>
          <p><%= link_to 'Message Designer', conversations_path %></p>



        </div>
        </div>
        <% end %>

      </div>
      </div>
    </div>

    </div>